### ISSUE TITLE
genesyscloud_team resource removes members even when attribute isn't defined

### ISSUE THREAD

**Issue by travistie1** [MyPureCloud/terraform-provider-genesyscloud#1016]
When defining a genesyscloud_team resource with the member_ids parameter not specified, still removes the associated members of the work team.

In the terraform doc it mentions if the member_ids parameter isn't specified the terraform provider won't touch the members associated.

Can this please be fixed in the next version?

**Comment by carnellj-genesys** [comment]
Hi Travistie1,

I have opened a ticket for this https://inindca.atlassian.net/browse/DEVTOOLING-592 and placed it into our backlog.  Our next Sprint starts on Tuesday of next week, so it probably won't be in this release, but I will work to make sure it gets prioritized on the next Sprint.  We do two-week sprints if everything goes well and we can resolve the issue, it should be available 3 weeks form now.

**Comment by dginty4** [comment]
Hi @travistie1, we just merged a fix for this, it will be available in the next version of the provider
