### ISSUE TITLE
Export issue with 1.37.0, its taking forever to export all

### ISSUE THREAD

**Issue by viniljose** [MyPureCloud/terraform-provider-genesyscloud#1023]
I tried the below config to export all GC Objects and its running for ever and i forcefully killed it after 3 hrs. With version 1.35.0 it takes around 1.5 hrs for full export.
```
terraform {
    required_version = ">= 1.5.6"
  required_providers {
    genesyscloud = {
      source  = "mypurecloud/genesyscloud"
      version = "1.37.0"
    }
  }
}
resource "genesyscloud_tf_export" "export" {
  directory          = "./genesyscloud"
  split_files_by_resource     = true
  include_state_file = true
  log_permission_errors = true
  export_as_hcl = true
  enable_dependency_resolution  = true
}
```

If I use below to get the CGR it downloads quickly
```
terraform {
    required_version = ">= 1.5.6"
  required_providers {
    genesyscloud = {
      source  = "mypurecloud/genesyscloud"
      version = "1.37.0"
    }
  }
}
resource "genesyscloud_tf_export" "export" {
  directory          = "./genesyscloud"
  split_files_by_resource     = true
  include_state_file = true
  log_permission_errors = true
  export_as_hcl = true
  enable_dependency_resolution  = true
  include_filter_resources = ["genesyscloud_routing_queue","genesyscloud_routing_queue_conditional_group_routing"]
}
```
Please let me know additional details is needed or not.
terraform version 1.5.6

**Comment by dginty4** [comment]
Hi @viniljose,

Thanks for bringing this to our attention, I will open a ticket for us to investigate this.

Regards,
Declan

**Comment by HemanthDogiparthi12** [comment]
Hi @viniljose 

If you want to export the entire ORG, may be you dont need enable_dependency_resolution  = true , while we check why it is taking more time compared to versions 1.35.0, can you remove this attribute and see if you are still able to export all the GC objects.

**Comment by viniljose** [comment]
Thank You @HemanthDogiparthi12 and @dginty4 for the quick reply
My use case is that I need to move code from one org to other org, I need the dependency for GC Objects so that it will help in order of creation of objects in other org.
I will remove 'enable_dependency_resolution = true' and see whether it helps

**Comment by viniljose** [comment]
It works with out 'enable_dependency_resolution = true'  and ENABLE_STANDALONE_CGR=true
```
resource "genesyscloud_tf_export" "export" {
  directory          = "./genesyscloud"
  split_files_by_resource     = true
  include_state_file = true
  log_permission_errors = true
  export_as_hcl = true
  }
```

**Comment by HemanthDogiparthi12** [comment]
Hi @viniljose 

Glad it worked for you. In order to troubleshoot further on the core problem with 'enable_dependency_resolution = true'
If possible can you help with below details 

- Can you open a care ticket and provide the logs for export with version 1.35.0 and the one which is long running in it.  Please do mention the forum thread in the details . 
- Can you try this ignore_cyclic_deps           = false and see if the export process finishes quick. if the process finishes/stops can you provide the export directory in a zip.

Need Both the above two options with 'enable_dependency_resolution = true'

Kind Regards
Hemanth

**Comment by viniljose** [comment]
Sorry for the late reply. 
I tried with 1.39.0 it is working without ENABLE_STANDALONE_CGR=true
I made enable_dependency_resolution  = true and downloaded all objects.

I will try with ENABLE_STANDALONE_CGR=true and update here, I feel issue is with this settings

**Comment by viniljose** [comment]
I tried in 1.40.1 version with ENABLE_STANDALONE_CGR=true  and below settings and worked. So closing the issue
+ resource "genesyscloud_tf_export" "export" {
      + directory                    = "./genesyscloud"
      + enable_dependency_resolution = true
      + export_as_hcl                = true
      + id                           = (known after apply)
      + ignore_cyclic_deps           = true
      + include_state_file           = true
      + log_permission_errors        = true
      + split_files_by_resource      = true
    }

**Comment by viniljose** [comment]
@HemanthDogiparthi12 @dginty4
