### ISSUE TITLE
From Email is not required

### ISSUE THREAD

**Issue by shane-genesys** [MyPureCloud/terraform-provider-genesyscloud#103]
https://github.com/MyPureCloud/terraform-provider-genesyscloud/blob/7d6783f3246776512ada8ba936018851da7df004/genesyscloud/resource_genesyscloud_routing_email_route.go#L121

From Email is not required in the GC UI and that is causing issues to use the export functionality since these aren't always defined.

**Comment by ronanwatkins** [comment]
Thanks for the PR. I'll merge it today and we'll be doing a release this week
