### ISSUE TITLE
genesyscloud_flow" "flow"

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#1068]
In this resource genesyscloud_flow"  I am trying to create a inbound flow called "newflow.yaml" and my cx-as-code was created in another file called flow.tf where i have my substitutions key value pare mentioned, 
when i push my code i am getting error saying 

pre-processor substitution key of '{{ substitutions.flow_name }}' was found in the flow YAML, but was not found in the options file.

where I need to keep the options file in  resource genesyscloud_flow ? your sample was not given like this 

will Options file support in Cx-AS-Code or only with Archy it will be supported.

Note - My use case was reference need to be external source using options.yaml' file.

**Comment by saravanakumar-rogers** [comment]
I have resolved all errors which i got earlier on Options.yaml file now i am getting below error, which i don't have clue, to check where this is getting break..  my flow is same as sample flow given in Archy documentation.  Can you please suggest 

│ ArchSession.startWithAuthToken - Caught unhandled exception during callback function execution.  Ending session.  Exception info: TypeError: Cannot read properties of undefined (reading 'refId').

**Comment by charliecon** [comment]
Hi @saravanakumar-rogers 

It is unusual for a CX as Code error to mention the options file. Were you running archy commands to deploy your flow? 

Could you search newflow.yaml for "refId", and if you find it, copy and paste that section here? It seems like there is a typo of some sort in the file. (be sure to remove sensitive data)

Thanks
Charlie
