### ISSUE TITLE
TF Export is given different order in each export

### ISSUE THREAD

**Issue by viniljose** [MyPureCloud/terraform-provider-genesyscloud#1085]
I do daily TF export and do some comparison to check if any changes in the file exists.
Many of GC Object resources content order is not the same if I do the export again in the next day, even with out any content change for the particular GC Object in UI.
This is making its difficult to find out if there are any changes in the resources.
Can we make the order of Export content same if there is no change in UI for particular GC Object. This happens every time for routing queue where as skills it works as expected(no change in TF if there is no change in UI).

Note
I know that TF plan will show there are no changes, but I need this to be part of export.

**Comment by carnellj-genesys** [comment]
Closing with as there is no further response.

**Comment by viniljose** [comment]
Thank You
