### ISSUE TITLE
replace_with_datasource when export keeps mode as managed in state file

### ISSUE THREAD

**Issue by eelhilali** [MyPureCloud/terraform-provider-genesyscloud#1153]
Hi,
When i export resources including state file and want to keep some as datasources, all resources in state file have managed mode.
So i need to update all datasources as mode=data manually.

**Comment by dginty4** [comment]
Hi @eelhilali 

I will create a ticket for this and we will take a look as soon as possible. Thanks for pointing this out.

Regards,
Declan

**Comment by eelhilali** [comment]
thanks @dginty4
here are some additional infos:
provider version = "~> 1.42.0"

resource example:

resource "genesyscloud_tf_export" "export" {
  directory = "./genesyscloud"
  replace_with_datasource = [
    "genesyscloud_routing_queue::EEL_Demo"
  ]

  include_filter_resources     = ["genesyscloud_routing_queue::EEL_*"]
  include_state_file           = true
  export_as_hcl                = true
  log_permission_errors        = true
  split_files_by_resource      = true
  ignore_cyclic_deps           = true
  enable_dependency_resolution = false
  compress                     = false
  exclude_attributes           = ["genesyscloud_routing_queue.members"]
}

**Comment by charliecon** [comment]
Fixed as of v1.44.0
