### ISSUE TITLE
Outbound Email Address

### ISSUE THREAD

**Issue by SavinoRicci** [MyPureCloud/terraform-provider-genesyscloud#1179]
We are using genesyscloud_routing_queue_outbound_email_address resource however any changes to genesyscloud_routing_queue removes the outbound email address from the queues. Does not show on plan that they are being removed. We are then having to manually add the address back via the UI.

**Comment by dginty4** [comment]
Hi @SavinoRicci,

Thanks for letting us know, we'll gte a ticket for this and have it fixed as soon as possible.

Regards,
Declan

**Comment by dginty4** [comment]
@SavinoRicci 

This issue has been fixed and will be available in the next version of the provider

Regards,
Declan

**Comment by SavinoRicci** [comment]
Fantastic, thank you!
