### ISSUE TITLE
trunk base media site availability?

### ISSUE THREAD

**Issue by asadsaqlain** [MyPureCloud/terraform-provider-genesyscloud#1215]
Due to the unavailability of trunk base media site we're facing some automation issues and my question to the team is when can we expect to have this feature available?

**Comment by carnellj-genesys** [comment]
Hi Asad,

I dont have a definitive answer yet.  I will add this to our backlog, but we will need to assess the difficulty of adding this and then prioritize.

Thanks,
   John

**Comment by asadsaqlain** [comment]
Hi John,

Thanks for picking it up. Do you have any update on this?

Cheers, Asad

**Comment by carnellj-genesys** [comment]
Its still in our backlog.  We just got another request for it so i am going to look at prioritizing it.  Dont have an ETA yet, but I will let you know

**Comment by carnellj-genesys** [comment]
Hi Asad,

This should be resolved with the latest release on Weds. Nov 6th.  Please let me know if you have any other issues.

Thanks,
    John

**Comment by asadsaqlain** [comment]
Hi John,

Thanks for the update. I see that the tag "site_id" is a string which is not correct, it should be a list of sites, and will also not help with implementation if the customer wants to add multiple sites and also prioritize one over the others.

Cheers, Asad

**Comment by carnellj-genesys** [comment]
Hi @asadsaqlain 

I saw the email you sent and I am bit confused.  The Post and Put 
/api/v2/telephony/providers/edges/trunkbasesettings API only accepts a single site_id as the media site id.  I had checked with the product managers and devs and media site is the site id field on the API.

Could you send me a screenshot of the specific field you are trying to set in the UI so I can go through and make sure we are on the fields.

Thanks,
    John

**Comment by asadsaqlain** [comment]
Hi John,

Sorry for the confusion. But that was a bit misunderstanding from my side you can ignore my previous post. 

Cheers, Asad

**Comment by carnellj-genesys** [comment]
Hi Asad,

No worries.  I had to have the product manager of the edge infrastructure team explain it to me (and I used to work on that team) so it is not always clear.

Thanks,
    John
