### ISSUE TITLE
"Description" field for Wrapupcodes

### ISSUE THREAD

**Issue by itsmanjax** [MyPureCloud/terraform-provider-genesyscloud#1243]
Hi Team,

We are getting "Description" field from Genesys Cloud API for "/api/v2/routing/wrapupcodes".

This field can be added in Terraform schema?

resource "genesyscloud_routing_wrapupcode" "win" {
  name = "Win"
}

Regards,
Manjunath

**Comment by carnellj-genesys** [comment]
Hi Manjunath, 

I will open a ticket ont it.  I cant give an ETA on it but I will someone address it.

Thanks,
   John
