### ISSUE TITLE
"genesyscloud_externalcontacts_contact" - "extension" field issue

### ISSUE THREAD

**Issue by itsmanjax** [MyPureCloud/terraform-provider-genesyscloud#1257]
Hi All,

Following is the generated terraform snippet for ExternalContact :

>             
                "title": "Senior Consultant",
                "work_phone": {
                    "display": "+91 808xx xxxxx",
                    "extension": 897,
                    "accepts_sms": true,
                    "e164": "+91808xxxxxxx",
                    "country_code": "IN"
                },
                "cell_phone": {
                    "display": "+91 974xx xxxxx",
                    "accepts_sms": true,
                    "e164": "+91974xxxxxxx",
                    "country_code": "IN"
                },
                "other_phone": {
                    "display": "+1 201-xxx-xxxx",
                    "accepts_sms": false,
                    "e164": "+1201xxxxxxx",
                    "country_code": "US"
                },
                "home_phone": {
                    "display": "+1 201-xxx-xxxx",
                    "accepts_sms": false,
                    "e164": "+1201xxxxxxx",
                    "country_code": "US"
                }

"**cell_phone**", "**other_phone**" and "**home_phone**" don't have "**_extension_**" field and as per the schema it's not an mandatory field.

But when run the script to deploy the object in another Genesys Cloud env, "**ext. 0**" is getting added to the above mentioned fields. (please refer to the enclosed screenshot)

**_![ExternalContacts](https://github.com/user-attachments/assets/23646245-6bff-4263-958a-d4f0fff815dd)_**

Please can you validate this.

Regards,
Manjunath

**Comment by carnellj-genesys** [comment]
Hi Itsjmax,

Im going to open a ticket with the team.  We can remove fields on the export if they are empty, so we just to look at implementing it the above fields.

Thanks,
    John

**Comment by charliecon** [comment]
Fixed in PR #1346 

Will be publicly released next week on v1.53.0
