### ISSUE TITLE
Version 0.13.2 genesyscloud_tf_export failed 

### ISSUE THREAD

**Issue by saravanakumar80** [MyPureCloud/terraform-provider-genesyscloud#160]
Hi team - while we attempt to export of complete Org using Terraform export option we are facing error 

we tried as below without specifying the resource type inside the tf_export. please suggest if any issue in our logic or this is a bug. ?

resource "genesyscloud_tf_export" "export" {
  directory          = "./terraform"
  
  include_state_file = true
  
}
==========================================================
Error: Plugin did not respond
│
│   with genesyscloud_tf_export.export,
│   on export.tf line 1, in resource "genesyscloud_tf_export" "export":
│    1: resource "genesyscloud_tf_export" "export" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-genesyscloud_v0.13.2.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1e99e4e]

goroutine 5288 [running]:
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.readUserPrompt.func1(0xf7062b)
        github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_architect_user_prompt.go:842 +0x64e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/resource/wait.go:27 +0x62
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc0012f9c20, 0xc00035a620, 0xc000b95aa0, 0xc000188900, 0xc00131e520, 0xc00131e4e8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/resource/state.go:110 +0x344
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/resource/state.go:83 +0x1d9

Error: The terraform-provider-genesyscloud_v0.13.2.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by ronanwatkins** [comment]
0.13.3 has been released with the fix
