### ISSUE TITLE
genesyscloud_tf_export - 0.14.0

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#175]
Hi Team - 

I am using Terraform Enterprise Workspace  Version 0.14.7 , where if we execute the genesyscloud_tf_export command it was showing successful however unbale to locate the Directory path where the file got created.

Please help how to export the Objects which was manually created inside Genesys ORG to bring inside the CICD Pipeline.
 
![image](https://user-images.githubusercontent.com/92093419/144433972-0c1bed9a-97dc-4ea8-8ba4-dcac42e75e91.png)

**Comment by ronanwatkins** [comment]
Hi,

If you omit the `directory` value in the `genesyscloud_tf_export` resource block then the directory will be named `genesyscloud` and will be located in the same directory as the file containing your export config.
You can include a `directory` containing a path to a directory to store the exported config.
Please see the documentation of this resource for more info: https://registry.terraform.io/providers/MyPureCloud/genesyscloud/latest/docs/resources/tf_export

**Comment by saravanakumar-rogers** [comment]
**Hi Ronan - thanks for the quick revert.  I am using Git Repo to host the export config .
so can i use Git Repo path to get the genesyscloud.tf.json ?

**Comment by saravanakumar-rogers** [comment]
have you tested this before with TFE or TFC , we are unable to locate the file in Git so please share if you have any documentation on the same.

**Comment by ronanwatkins** [comment]
I haven't tried this with TFE or TFC.
Can you confirm that you are checking the file on the CI runner after the export has been completed? The runners are ephemeral and the file will disappear along with the runner after the job completes if it is not stored somewhere.
If you continue to have issues after confirming this then we can test this feature with TFE and TFC

**Comment by ronanwatkins** [comment]
Before I start looking into this can you confirm that it works locally on your machine?

**Comment by saravanakumar-rogers** [comment]
Yes - Working fine locally without any issues , in that method i am exporting object by object from Prod Org 
to Test Org. Since my client 1st went production with one business and not newly signed for Test Org.

**Comment by ronanwatkins** [comment]
I tried using a terraform workspace and it seems that it's not possible to execute a script on the runner and upload files from it. Therefore this feature isn't suited to that situation.
You should export the organization by running the terraform CLI locally.
