### ISSUE TITLE
Bug when exporting users

### ISSUE THREAD

**Issue by segestaconsult** [MyPureCloud/terraform-provider-genesyscloud#181]
This bug occurs when users have only an extension assigned in their profile (not DID)

see:
https://developer.genesys.cloud/forum/t/cx-as-code-bug-when-exporting-users-resource-genesyscloud-user/12971

**Comment by ronanwatkins** [comment]
Hi,

I'm after looking into this bug. I should have a fix out within the next 2 weeks.

**Comment by ronanwatkins** [comment]
@segestaconsult Version 1.0.1 has just been released. It contains a best effort fix for this issue. If this does not fix your problem or causes other unintended consequences we will have to ask the team behind the users API to make some changes.
