### ISSUE TITLE
creating schedule and schedule group via CX-As-Code

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#190]
While creating schedule and schedule group there is no parameter to choose division , by default it is getting created in Home division.
How can we add division in schedule and schedule group using CX-As-Code ?

**Comment by saravanakumar-rogers** [comment]
Team waiting for your fix on this terraform schedule and schedule group schema issue - 
I checked the GET API is able to fetch the division name and id but you are used as parameter in scheduling .
Can this be fixed please.

**Comment by ronanwatkins** [comment]
Hi,

This has been released in a previous release
