### ISSUE TITLE
genesyscloud_tf_export and genesyscloud_group_roles

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#193]
Hi team 
if we use genesyscloud_tf_export for genesyscloud_group and genesyscloud_group_roles the export json file presenting the same resource name (genesyscloud_group) for both objects

group_roles
![image](https://user-images.githubusercontent.com/92093419/150820183-a3cf8b89-a450-4853-a5ab-68c486515ec1.png)

group
![image](https://user-images.githubusercontent.com/92093419/150820275-c61a0379-b459-4294-8592-338c1051610c.png)

this will impacting us doing terraform import , can you fix the export resource name to **genesyscloud_group_roles** on this please.

**Comment by ronanwatkins** [comment]
Hi,

The body of the second screenshot titled group_roles contains a group resource.
Group roles only have 2 properties - group_id and roles.
I tried to reproduce your issue but my export was successful. See the below screenshot:
![image](https://user-images.githubusercontent.com/7252200/150829978-c2dacd3c-5720-4e56-8431-3eda903e61e5.png)

**Comment by saravanakumar-rogers** [comment]
thanks ronan. please let any difference in my export ? i am not sure why i am not seeing the resource name like you .. 

my export code using version 1.0.2 
![image](https://user-images.githubusercontent.com/92093419/150947054-568884de-6bc6-4d1d-88ae-7da217c226e3.png)

![image](https://user-images.githubusercontent.com/92093419/150947087-60f72f81-b010-4c73-8f51-4b26677e72a9.png)

**Comment by saravanakumar-rogers** [comment]
thanks i got the same resource name in bottom of the file , group  roles also exporting both groups and roles 

![image](https://user-images.githubusercontent.com/92093419/150957121-d1d10185-76cf-45d7-8120-35f48a1ba190.png)

now we can close this issue.
