### ISSUE TITLE
problem with resource genesyscloud_architect_user_prompt 1.1.1

### ISSUE THREAD

**Issue by motomeru** [MyPureCloud/terraform-provider-genesyscloud#212]
Hey, 

problem reproduction:

create new resource on version **1.1.1**

resource "genesyscloud_architect_user_prompt" "languageSelection4" {
  name        = "Test_Welcome_Message"
  description = "Test"
    resources {
    language = "en-ca"
    filename =  "testCiCd.wav"
  }
}

after terraform apply commands new prompt will be created but without wave file, via API i see:

      "id": "en-ca",
      "promptId": "XXX",
      "language": "en-ca",
      **"uploadStatus": "created",**

--------------------------------------------------------------------------------

when I reproduce this steps on 0.14.1 everything is working- after terraform apply command I have new prompt with wav file, on working scenario i see also diffrence on API:

      "id": "en-ca",
      "promptId": "XXX",
      "language": "en-ca",
      "mediaUri": "https://prod-euc1-audio-prompts.s3.eu-central-XX",
      **"uploadStatus": "transcoded",**

**Comment by ronanwatkins** [comment]
Hi,

This issue will be fixed in a future release. For now, if you use a relative or absolute path to the `filename` it will work.

**Comment by motomeru** [comment]
Hey, thank you very much

**Comment by motomeru** [comment]
Hey Ronan, I checked new release version 1.3.0 but I have the same error - file is not imported to GC upload status should be transcoded but with terraform import I have only  "uploadStatus": "created"

I cannot use absolute path ( I store .wav files on github )

**Comment by ronanwatkins** [comment]
Hi @motomeru 

Version 1.4.0 has just been released and this contains a definite fix

**Comment by motomeru** [comment]
HI, 

I changed version to 1.4.0 but still have the same problem

Error that I received:
`
Error: prompt file not transcoded
with genesyscloud_architect_user_prompt.WelcomeTf
on genesyscloud_architect_user_prompt.tf line 500, in resource "genesyscloud_architect_user_prompt" "WelcomeTf"
`
TF file configuration

`resource "genesyscloud_architect_user_prompt" "WelcomeTf" {
  name        = "Welcometf"
  description = "Welcometf"
  resources {
    language   = "en-us"
    filename = "prompts/recordings/Welcome.wav"
  }
  resources {
    language   = "es-us"
  }
}`

**Comment by ronanwatkins** [comment]
Hi,

Apologies for the delayed reply on this. I have tested this locally with our [test wav file](https://github.com/MyPureCloud/terraform-provider-genesyscloud/blob/main/genesyscloud/test-prompt-01.wav) without issue.
Have you been able to successfully use this wav file using the API separately or the user interface?

**Comment by motomeru** [comment]
HI @ronanwatkins ,

I can confirm it's working right now! 

Thank you very much
