### ISSUE TITLE
genesyscloud_architect_schedules - Start and End Time keep changing

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#213]
Hi Team - 
we observed that object which created via C-As-Code genesyscloud_architect_schedules , is keep getting same change on every build of another objects. 
we could see this behavior in 2 objects **genesyscloud_architect_schedules and genesyscloud_auth_role**

![image](https://user-images.githubusercontent.com/92093419/157422946-28dee0c5-2ace-4597-b61c-90584e370279.png)

Please help us to know why this changes appearing in the files when we have done those changes those codes .

**Comment by saravanakumar-rogers** [comment]
Note :  For genesyscloud_architect_schedules you have added divisions as a optional parameter. however when we try to check via terraform state it showing divisions are unsupported parameter. why ?

![image](https://user-images.githubusercontent.com/92093419/157428377-27436f9f-e087-4507-bc7c-eb47ade80a10.png)

**Comment by AgnesCorpuz** [comment]
Hi,

Can you please share steps to recreate the issue? Thanks,

**Comment by saravanakumar-rogers** [comment]
Hi, - 
1. Create genesyscloud_architect_schedules via CX-As-Code with Division -ID. 
2.  Access the Terraform state file using CLI and Try to  see the Code which you created via CX-AS-Code through CLI.  
3. the output will not be appearing reason the Division ID which used in the code causing issue.

**Comment by AgnesCorpuz** [comment]
Can you confirm if the Division is already existing on your Genesys Cloud org? If it is, we are recommending using data source for already existing objects. You may find the documentation how to use it [here](https://developer.genesys.cloud/api/rest/CX-as-Code/). Otherwise, can you please share the .tf file to help us with the investigation.

**Comment by saravanakumar-rogers** [comment]
Yes Division is exits and the code working fine, but we did it via variable for division not via data source. My ask in this issue is if we use division-id in genesyscloud_architect_schedules parameter, why it is showing unsupported parameter when we try to display the code using Terraform CLI with state show command, where other resources are showing correctly.?

**Comment by carnellj** [comment]
Closing this item due to inactivity
