### ISSUE TITLE
Bug when exporting org

### ISSUE THREAD

**Issue by richkramp** [MyPureCloud/terraform-provider-genesyscloud#243]
Attempting to export an org

Config File
`
resource "genesyscloud_tf_export" "export" {
  directory          = "."
  include_state_file = true
  export_as_hcl          = true
}
`

Stack trace from the terraform-provider-genesyscloud_v1.1.3 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe59e59]

goroutine 169046 [running]:
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.readQueue.fu                                                                                                                                                             nc1(0x2)
        github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/reso                                                                                                                                                             urce_genesyscloud_routing_queue.go:441 +0x699
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1(                                                                                                                                                             0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/resource/wai                                                                                                                                                             t.go:27 +0x5b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).                                                                                                                                                             WaitForStateContext.func1(0xc000c523c0, 0xc00428e230, 0xc00316b200, 0xc0040dd280                                                                                                                                                             , 0xc000c4d478, 0xc000c4d470)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/resource/sta                                                                                                                                                             te.go:110 +0x2e9
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateC                                                                                                                                                             hangeConf).WaitForStateContext
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/resource/sta                                                                                                                                                             te.go:83 +0x1c6

Error: The terraform-provider-genesyscloud_v1.1.3 plugin crashed!

**Comment by ronanwatkins** [comment]
Hi,

Looks like it crashed on the line setting the new name. It didn't check that the if the name was null because it was assumed name was a required property.
I will push up a fix for this now and we will release it with the next release of the provider.

**Comment by richkramp** [comment]
If it helps, I was performing an export when this error occurred.

Thanks,

Rich Kramp
Sr. Principal Consultant, Professional Services
