### ISSUE TITLE
genesyscloud_group - Roles 

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#262]
Hi Team - 

In Genesys Console UI - we can see toggle button for Enable Roles ON / OFF , where we assign any roles to the Group via CX-As-Code this button getting turned off. also need to know which parameter will help me to set ON via CX-As-Code. ?

![image](https://user-images.githubusercontent.com/92093419/169057751-730f100c-bcf0-4691-92f2-de0506364104.png)

**Comment by ronanwatkins** [comment]
Hi @saravanakumar-rogers,

It appears that this behaviour isn't exposed by our API but I will double check with the team responsible and get back to you.

**Comment by ronanwatkins** [comment]
Hi @saravanakumar-rogers,

This isn't exposed via our API. The best way to make the relevant product manager aware of this is to create an idea on our [ideas portal](https://genesyscloud.ideas.aha.io/ideas). It may be picked up then and added to a future release of the API.

**Comment by saravanakumar-rogers** [comment]
thank you
