### ISSUE TITLE
genesyscloud_architect_schedules

### ISSUE THREAD

**Issue by motomeru** [MyPureCloud/terraform-provider-genesyscloud#271]
Hey, I try to create new schedule:

one from your example from terraform page:
`resource "genesyscloud_architect_schedules" "test_schedule" {
  name        = "CX as Code Schedule"
  description = "Sample Schedule by CX as Code"
  start       = "2021-08-04T08:00:00.000000"
  end         = "2021-08-04T17:00:00.000000"
  rrule       = "FREQ=DAILY;INTERVAL=1"
}`

on terraform apply it's ending with error:

![image](https://user-images.githubusercontent.com/10912411/171054010-2dbf28e6-1fe8-4e45-b508-b729cc7e57b3.png)

the same error I have on rrule that I uploaded directly from API:
`rrule       = "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR"`

I use genesys cloud package 1.3.0

Warm regards,
Dawid

**Comment by ronanwatkins** [comment]
Hi Dawid,

I have successfully created schedules with the following config:
```
resource "genesyscloud_architect_schedules" "test_schedule" {
  name        = "CX as Code Schedule"
  description = "Sample Schedule by CX as Code"
  start       = "2021-08-04T08:00:00.000000"
  end         = "2021-08-04T17:00:00.000000"
  rrule       = "FREQ=DAILY;INTERVAL=1"
}
```
and
```
resource "genesyscloud_architect_schedules" "test_schedule" {
  name        = "CX as Code Schedule"
  description = "Sample Schedule by CX as Code"
  start       = "2021-08-04T08:00:00.000000"
  end         = "2021-08-04T17:00:00.000000"
  rrule       = "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR"
}
```
If you cannot create schedules using those configurations I recommend using the following config for the provider:
```
provider "genesyscloud" {
  sdk_debug = true
  ...
}
```
and getting the correlationId of the failed request. You could then create a ticket with Care and provide them with the correlationId to investigate.
