### ISSUE TITLE
failed to get page of process automation triggers: API Error: 403

### ISSUE THREAD

**Issue by k3s4** [MyPureCloud/terraform-provider-genesyscloud#277]
Hello,

I'm struggling with authorization method which I should use for "genesyscloud_tf_export" for now I have setup "Client Credentials" as it's described in documentation - https://developer.genesys.cloud/devapps/cx-as-code/#terraform but it gives me following error:
```
Error: failed to get page of process automation triggers: API Error: 403 - Unable to perform the requested action. You must have at least one of the following permissions assigned: [processautomation:trigger:edit, processautomation:trigger:view] (39e6254f-f28b-4733-9dc9-d8c5443ccd02)
To continue exporting other resources in spite of this error, set the 'log_permission_errors' attribute to 'true'
```

from what I know these permissions can be only applied for "Code Authorization" 

What I want to achieve is to simply export as much as I can from current configuration without using setting 'log_permission_errors' attribute to 'true'

**Comment by carnellj** [comment]
Hi Kamil,

The error you are getting is related to the fact that process automation triggers are currently behind a closed beta.  If you are not part of the beta you will get a 403 any time Terraform tries to do anything with the process automation triggers resource on an export.  It has nothing to do with the particular OAuth grant you are using. 

In this particular case go ahead and set the `log_permission_errors` to true and then monitor the export.  If this is the only error that is coming up then everything is working as designed.

Thanks,
    John Carnell
