### ISSUE TITLE
Routing Queue - queue_flow_id - Not Updating for Message & Email 

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#310]
Hi Team 

This for **genesyscloud_routing_queue (Resource)**

The Queue_flow_Id parameter only works with Voice and does not update the Message & Email media within Queue. 

[queue_flow_id] - (String) The in-queue flow ID to use for call conversations waiting in the queue.

Please let me know how to use queue_flow_id in Messages and Emails.

**Comment by ronanwatkins** [comment]
Hi,

The `email_in_queue_flow_id` and `message_in_queue_flow_id` are used for emails and messages respectively.

**Comment by saravanakumar-rogers** [comment]
I agree - The ask is when I try to update queue_flow_id for Message or Email it not updating it is updating only for Voice in a Queue. 

Please confirm if this is working as excepted that queue_flow_id for Message in a Queue. can be updated via CX-As-Code.
