### ISSUE TITLE
Groups - genesyscloud_group

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#315]
Hello Team -
Under which parameter in terraform cx-as-code do we need to enable the "Enable Calls" option in the Group config? 

Also how to configure only with "extension" in the Cx-As-Code currently number and extension need to be added via code ad than in the UI we are removing the number.  If we code only with the extension we are facing an error. 

Also, these below options are not available in CX-As-Code.
- Call Route Type has 3 options in UI we can't match all parameters in Cx-As-Code.
- Rotate Calls we can't match all parameters in Cx-As-Code.
- Stop Ringing we can't match all parameters in Cx-As-Code.
-  Overflow option we are unable to code via Cx-As-Code.

![image](https://user-images.githubusercontent.com/92093419/181069184-bfb668d0-d5bb-47cc-9eb0-2ddd768c4c27.png)

**Comment by carnellj-genesys** [comment]
Hi Saravana,

I did some research.  The reason why they do not show up in the CX as Code resource is that the information you are highlighting is not part of the group API, but the voicemail API. I suspect the UI team incorporated the two different sets of data into the same screen to streamline the group creation process.

We currently do not have any of the voicemail resources exposed in CX as Code.  I am going to open a ticket internally and work with our product manager to figure out where and when this should be released on the overall priority list.  I know your team works with Jeremy, so I will keep him in the loop as new information arises and we get a better ETA on this.

Thanks,
     Johb

**Comment by pflugs30** [comment]
As I convert several of our resources to CX as Code templates, I've run across Groups with `Enable Calls` set to `true`.  Can we do this in CX as Code yet?  Thanks!
