### ISSUE TITLE
genesyscloud_architect_datatable

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#321]
Hi Team - 

We tried to rename the existing Property value but we got an error saying - 
![image](https://user-images.githubusercontent.com/92093419/181766678-828c2e22-3f86-4c7e-ab12-ed29ee7d158c.png)
 
How to rename the Properties if required via Cx-As-Code.? Please suggest

**Comment by ronanwatkins** [comment]
Hi,

According to the description for `properties`: `Properties cannot be removed from a schema once they have been added`.
We should have marked a property name as `ForceNew` because of this. I will update this and include it in the next release.
