### ISSUE TITLE
genesyscloud_architect_schedulegroups

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#322]
Hello Team -

In the Cx-As-Code Schema - it is mentioned - genesyscloud_architect_schedulegroups only name is required attribute.
 However, when we create schedule groups only with the name it is giving error saying " API Error 400  Schedule Groups  require at least one open schedule" 

But in the schema, it was mentioned all schedule IDs are OPTIONAL. Can you make these parameters optional and allow us to create the blank Schedule Group?

**Comment by ronanwatkins** [comment]
Hi,

Since the error is coming from the API there is nothing we can do regarding making that property optional.
We can and will mark it as required in the provider though so thanks for raising that issue.

**Comment by saravanakumar-rogers** [comment]
Thanks, Rohan - So can I update the client saying in the next release the Optional will be working as same as Groups / Queues where members' can be ignored while creating the resources? Please confirm.

**Comment by ronanwatkins** [comment]
`open_schedules_id` will be updated to Required in the next release to bring it in line with API behaviour.

**Comment by saravanakumar-rogers** [comment]
No, we are looking for optional so that schedule groups can be created without any open, closed, & holiday schedule _id, and we will update the schedule_id association to schedule groups via GUI.

Reason --
the Schedules -ID  assignment to Schedule groups is managed by the business, hence moving this to Cx-As-Code in CI/CD will be difficult.
So please keep this optional and make API to create the Schedules Groups  Without Schedules -ID

**Comment by ronanwatkins** [comment]
If you require a change to API behaviour then the best thing to do is create a feature request on our [ideas portal](https://genesyscloud.ideas.aha.io/portal_session/new) and explain your use case.
If it is accepted and changed then we will update the `open_schedules_id` to optional in line with their change.

**Comment by saravanakumar-rogers** [comment]
Thanks, Ronan - I have raised this in the idea portal. I request you to consider this flexibility, the same flexibility you have already provided for Groups / Queues for Members association.

**Comment by ronanwatkins** [comment]
I'm not aware of a specific vote target but encouraging others that you work with who may be interested in this feature to vote will always help.

**Comment by saravanakumar-rogers** [comment]
please let me know is the feature will be added to Cx-As-Code
