### ISSUE TITLE
recording_media_retention_policy

### ISSUE THREAD

**Issue by motomeru** [MyPureCloud/terraform-provider-genesyscloud#340]
Hi Genesys Team,

We are trying to export our policies to Terraform, unfortunately in resource object you are using Cross Platform API:

[GET /api/v2/recording/crossplatform/mediaretentionpolicies/{policyId}]
[GET /api/v2/recording/crossplatform/mediaretentionpolicies]
[PUT /api/v2/recording/crossplatform/mediaretentionpolicies/{policyId}]
[POST /api/v2/recording/crossplatform/mediaretentionpolicies]
[DELETE /api/v2/recording/crossplatform/mediaretentionpolicies/{policyId}]

we don't see that permission for cross platform API in Genesys Cloud UI, so we cannot add that permissions to specific roles, can you review that from your side? We checked that in few GC orgs EMEA and US West regions.

PRTSC from GC documentation: https://prnt.sc/G4_8bNXyQ6X-
PRTSC from GC UI: https://prnt.sc/og8w-Jvy9yVg

Warm regards,
Dawid

**Comment by ronanwatkins** [comment]
Hi Dawid,

The minimum licenses needed for recording permissions are `Digital Essentials I` and `Cloud CX 3`.

If you do not have either of these please follow the appropriate channels to have them added to your GC org.

Best regards,
Ronan

**Comment by motomeru** [comment]
Hi Ronan,

I checked my org and user via /api/v2/license/users/ and I have DX1 and CX3 license and still don't see in UI Crossplatform permission.

each API request is ending:

`{
  "message": "Unable to perform the requested action. You must have at least one of the following permissions assigned: [recording:crossPlatformRetentionPolicy:view]",
  "code": "missing.any.permissions",
  "status": 403,
  "contextId": "6fcdb1de-0e62-41da-8187-d44a2eb1182e",
  "details": [],
  "errors": []
}`


Could you review if in your dev organization that you see that permission? I checked that also with other GC partners and they also don't see that permissions...

Warm regards,
Dawid

**Comment by carnellj-genesys** [comment]
Hi Dawid,

I am going to close this issue you out.  If you are still having problems with permissions, I would open a ticket with our Care team.

Thanks,
    John Carnell
    Manager, Developer Engagement
