### ISSUE TITLE
Provider Plugin Version 1.1.3

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#343]
CI/CD Pipeline gives an error while downloading the mypurecloud/Genesys cloud provider plugin version 1.1.3

let me know if this version is still there are removed from https://registry.terraform.io/. What is the retention for Old Provider Plugins versions? 

![image](https://user-images.githubusercontent.com/92093419/188889283-32c99b18-c8e7-4acd-9d25-6c03718439b3.png)

**Comment by ronanwatkins** [comment]
I'm not seeing that issue when I try to replicate it. You should use the latest version (`v1.5.0`). This has more features and is more performant
