### ISSUE TITLE
Issue with genesyscloud_flow_outcome

### ISSUE THREAD

**Issue by Isusko-Sallen-Latatu** [MyPureCloud/terraform-provider-genesyscloud#360]
There is an issue with the creation of the resource Flow Outcome with Terraform. The error message says that it  cannot validate due to missing description and in the official documentation says that the description is optional. 

It is a big trouble for us because we are trying to export massively the Flow Outcomes from an organization to another organization and most of the Flow Outcomes don't have a description, so we cannot automate the process. Please give us some feedback on the bug.

Thanks beforehand!

![9264f5c0-397c-4dfa-bb65-63600a3722a7](https://user-images.githubusercontent.com/113520396/194280354-212c711c-3ece-4e4b-80be-a70d60b3808d.jpg)

**Comment by carnellj-genesys** [comment]
Hi Isusko,

Thanks for letting us know.  I am having a developer take a look at it now.  If it turned out that it really is just an optional vs. the required field, this is a very minor change and we will try to get it into the release that is about to go out the door today or tomorrow.

If for some reason you can't wait for this it is possible to clone the repository and make the fix yourself and build it locally.  (I know this is not ideal, but I have recommended this to people if they can not wait for a fix.)

Thanks,
    John Carnell
     Manager, Developer Engagement

**Comment by Isusko-Sallen-Latatu** [comment]
Hello John,

Firstly I much appreciate your quickness on the topic. Currently we are developing a solution to automate the export of objects and Flow in Genesys and found this Little problema while working on it.

Thank you for the update. We cannot change the source code because we are a bit unexperienced with it so we will wait for the release of the update.

Thanks a lot,

[minsait]<http://www.minsait.com/>

Isusko Sallen Latatu
Cloud Consultant

Ribera de Axpe, 11
48950 Erandio. Vizcaya, España
T +34 94 481 82 00


De: carnellj-genesys ***@***.***>
Enviado el: jueves, 6 de octubre de 2022 16:23
Para: MyPureCloud/terraform-provider-genesyscloud ***@***.***>
CC: Sallen Latatu, Isusko ***@***.***>; Author ***@***.***>
Asunto: Re: [MyPureCloud/terraform-provider-genesyscloud] Issue with genesyscloud_flow_outcome (Issue #360)


Hi Isusko,

Quick update. It turns out the problem is in the REST endpoint that our CX as Code provider calls. Even though the field is supposed to be optional, the code in the service throws an exception if the value passed to is null (which is how the Java library treats fields that are not passed into as ). The service team needs to fix this problem in the service.

We (the CX as Code team) can put a small workaround in CX as Code to set the field to an empty string or a single-space string if it encounters no value for the description field. One of the engineers on my team is working on it now and we hope to have it out in the next release of the CX as Code provider (which should be today or tomorrow).

Thanks,
John Carnell
Manager, Developer Engagement

-
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMyPureCloud%2Fterraform-provider-genesyscloud%2Fissues%2F360%23issuecomment-1270146279&data=05%7C01%7Cisallen%40minsait.com%7C3fa4a7b0829942a1474608daa7a65311%7C7808e00514894374954bd3b08f193920%7C0%7C0%7C638006630041165207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6ZqSFk4t8Apom5sVjh3awk2QHSkgsIJXRjaJM6y2fSg%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA3CC6DFDC7WADR26FE4MI4LWB3ODPANCNFSM6AAAAAAQ6NWI2E&data=05%7C01%7Cisallen%40minsait.com%7C3fa4a7b0829942a1474608daa7a65311%7C7808e00514894374954bd3b08f193920%7C0%7C0%7C638006630041165207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eH0QdI8XoAPRSnsl9kH9SlFIGqKdnD5KPgx8FY8YyTk%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________

Este correo electrónico y, en su caso, cualquier fichero anexo al mismo, contiene información de carácter confidencial exclusivamente dirigida a su destinatario o destinatarios. Si no es vd. el destinatario indicado, queda notificado que la lectura, utilización, divulgación y/o copia sin autorización está prohibida en virtud de la legislación vigente. En el caso de haber recibido este correo electrónico por error, se ruega notificar inmediatamente esta circunstancia mediante reenvío a la dirección electrónica del remitente.
Evite imprimir este mensaje si no es estrictamente necesario.

This email and any file attached to it (when applicable) contain(s) confidential information that is exclusively addressed to its recipient(s). If you are not the indicated recipient, you are informed that reading, using, disseminating and/or copying it without authorisation is forbidden in accordance with the legislation in effect. If you have received this email by mistake, please immediately notify the sender of the situation by resending it to their email address.
Avoid printing this message if it is not absolutely necessary.

**Comment by carnellj-genesys** [comment]
Hi Isusko,

We have released the latest terraform provider with the bug fix above.  Here are the release notes:  https://github.com/MyPureCloud/terraform-provider-genesyscloud/releases/tag/v1.7.0.

Please let me know if you and further questions or concerns.

Thanks,
     John Carnell
     Manager, Developer Engagement

**Comment by Isusko-Sallen-Latatu** [comment]
Good morning John,

Me and my team were excited for seeing your email notifying us about the update. The first thing we've done today was to test if everything worked correctly and so it was. I attach a screenshot to verify that we could upload a Flow outcome without a description without any problems:

***@***.***

Thank you so much to you and your team specially to @dginty4<https://github.com/dginty4> who fixed the bug for us,


[minsait]<http://www.minsait.com/>

Isusko Sallen Latatu
Cloud Consultant

Ribera de Axpe, 11
48950 Erandio. Vizcaya, España
T +34 94 481 82 00


De: carnellj-genesys ***@***.***>
Enviado el: jueves, 6 de octubre de 2022 19:08
Para: MyPureCloud/terraform-provider-genesyscloud ***@***.***>
CC: Sallen Latatu, Isusko ***@***.***>; Author ***@***.***>
Asunto: Re: [MyPureCloud/terraform-provider-genesyscloud] Issue with genesyscloud_flow_outcome (Issue #360)


Hi Isusko,

We have released the latest terraform provider with the bug fix above. Here are the release notes: https://github.com/MyPureCloud/terraform-provider-genesyscloud/releases/tag/v1.7.0<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMyPureCloud%2Fterraform-provider-genesyscloud%2Freleases%2Ftag%2Fv1.7.0&data=05%7C01%7Cisallen%40minsait.com%7C392447872dcf4cb96fb608daa7bd568f%7C7808e00514894374954bd3b08f193920%7C0%7C0%7C638006728887153627%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l7sSFgxdpru3mIO68bY9DmqLI8YAAlaK1i1P1KYkJ2Y%3D&reserved=0>.

Please let me know if you and further questions or concerns.

Thanks,
John Carnell
Manager, Developer Engagement

-
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMyPureCloud%2Fterraform-provider-genesyscloud%2Fissues%2F360%23issuecomment-1270420882&data=05%7C01%7Cisallen%40minsait.com%7C392447872dcf4cb96fb608daa7bd568f%7C7808e00514894374954bd3b08f193920%7C0%7C0%7C638006728887309848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t%2F%2BYdn4D4Gn6Vq%2B79GHHL%2FY%2FCJ6IrvCNy2AfkSVIlXQ%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA3CC6DCFYVJYBJIYWADUKKTWB4BNTANCNFSM6AAAAAAQ6NWI2E&data=05%7C01%7Cisallen%40minsait.com%7C392447872dcf4cb96fb608daa7bd568f%7C7808e00514894374954bd3b08f193920%7C0%7C0%7C638006728887309848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nAAjpJSyxt3fPcCd1Wu7R5lNHjZxSxqHlTjHschaO8o%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________

Este correo electrónico y, en su caso, cualquier fichero anexo al mismo, contiene información de carácter confidencial exclusivamente dirigida a su destinatario o destinatarios. Si no es vd. el destinatario indicado, queda notificado que la lectura, utilización, divulgación y/o copia sin autorización está prohibida en virtud de la legislación vigente. En el caso de haber recibido este correo electrónico por error, se ruega notificar inmediatamente esta circunstancia mediante reenvío a la dirección electrónica del remitente.
Evite imprimir este mensaje si no es estrictamente necesario.

This email and any file attached to it (when applicable) contain(s) confidential information that is exclusively addressed to its recipient(s). If you are not the indicated recipient, you are informed that reading, using, disseminating and/or copying it without authorisation is forbidden in accordance with the legislation in effect. If you have received this email by mistake, please immediately notify the sender of the situation by resending it to their email address.
Avoid printing this message if it is not absolutely necessary.

**Comment by carnellj-genesys** [comment]
Hi Isusko,

I will pass your thanks on to Declan :).  Glad we could fix it.  I am going to close this issue then.

- John
