### ISSUE TITLE
Issue with genesyscloud_integration_action

### ISSUE THREAD

**Issue by Isusko-Sallen-Latatu** [MyPureCloud/terraform-provider-genesyscloud#366]
Hello, I am opening this issue which is very similar to the last issue I opened #360. We are trying to do a export of an integration action automatically but we are having a little problem. When we are creating a genesyscloud_integration_action resource it requests us to send an integration_id while in the official Terraform documentation says it's not mandatory.

![db9ade9d-67ea-45b1-80f1-f3d3de601927](https://user-images.githubusercontent.com/113520396/195606396-75847d50-6f43-40ed-aa41-5fcce6155809.jpg)

![2f17e352-be2f-432c-b2e2-660268a9908e](https://user-images.githubusercontent.com/113520396/195606320-0a0462fb-b54d-4e8b-87ee-4baf356d3cf3.jpg)

![0a9ecbe1-8689-410f-880d-bd2f14e035d8](https://user-images.githubusercontent.com/113520396/195608158-6a152977-7bb7-4b5c-b544-d1a5e44fc9ef.jpg)

When we create the resource when the integration_id field fulfilled, then it works correctly. Would be nice if you could fix this :-)

Sorry for not noticing this last week. 

Thanks beforehand!

**Comment by charliecon** [comment]
Hi Isusko! 

Thanks for raising this issue. You're correct; `integration_id` should have been marked as required. I'll let you know here when this is corrected. 
Until then, if you're not already aware, you can ensure the integration_id is included in the export by setting `include_state_file` to `true`, or by including `genesyscloud_integration` in the `resource_types` array.

Thanks,
Charlie

**Comment by charliecon** [comment]
@Isusko-Sallen-Latatu This field has been changed to required as of v1.8.0
