### ISSUE TITLE
genesyscloud_routing_queue-bullseye_rings

### ISSUE THREAD

**Issue by saravanakumar-rogers** [MyPureCloud/terraform-provider-genesyscloud#388]
Hi Team - 

In Genesys UI - we are getting Add ring option to add other skills whereas in Cx-As-Code we are unable to add this option.

![image](https://user-images.githubusercontent.com/92093419/201436597-8af50e30-02d7-449b-b647-fa88b758664b.png)

Let us know how can we use this Add ring in terraform coding.

We tried to do 2nd skill via Add ring in UI but the Cx-as-Code removes my 1st skill and gets added my 2nd skill in 1st position. 

**Hence we need an urgent fix for this issue.**

**Comment by carnellj-genesys** [comment]
Hi guys,

Thanks for letting me know.  I will be working with Jeremy on getting more details on this.

Thanks,
    John Carnell
    Manager, Developer Engagement

**Comment by carnellj-genesys** [comment]
Closing this issue as this is not a defect (though it can be documented better) and Jeremy has provided a workaround

**Comment by carnellj-genesys** [comment]
We have modified the bulleyes_ring to now automatically add a default ring.  This means you can only define a maximum of 5 bullseye rings and you no longer have to add a dummy ring if you had less then 6 items.  Please watch the release notes for further instructions.
