### ISSUE TITLE
genesyscloud_tf_export - export specific division data

### ISSUE THREAD

**Issue by sienikam** [MyPureCloud/terraform-provider-genesyscloud#389]
Hello,

Is there a way to export data using 'genesyscloud_tf_export' resource for selected 'Division' ?
I see by default it's only exporting 'Home' division.

**Comment by carnellj-genesys** [comment]
Hi sienikam,

The OAuth client needs to have a role that is visible across multiple divisions.  If the role of your OAuth Client only has the home division assigned to it (which is the default division, that will be the only division you should be able to see.

Thanks,
     John Carnell
     Manager, Developer Engagemenent

**Comment by sienikam** [comment]
> Hi sienikam,
> 
> The OAuth client needs to have a role that is visible across multiple divisions. If the role of your OAuth Client only has the home division assigned to it (which is the default division, that will be the only division you should be able to see.
> 
> Thanks, John Carnell Manager, Developer Engagemenent

That was the issue, thanks :)

**Comment by carnellj-genesys** [comment]
Hi Sienikam,

Excellent.  Glad I was able to help.

Thanks,
     John
