### ISSUE TITLE
plugin crashed while exporting genesyscloud_auth_role

### ISSUE THREAD

**Issue by sienikam** [MyPureCloud/terraform-provider-genesyscloud#395]
Hello,

I have issue with exporting data using "genesyscloud_tf_export" and resource type "genesyscloud_auth_role" 

```
genesyscloud_tf_export.export: Creating...
╷
│ Error: Plugin did not respond
│
│   with genesyscloud_tf_export.export,
│   on main.tf line 18, in resource "genesyscloud_tf_export" "export":
│   18: resource "genesyscloud_tf_export" "export" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-genesyscloud_v1.9.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd2b84c]

goroutine 576 [running]:
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.flattenRoleConditionOperands({0xc0002cb000, 0x3, 0x10c117a?})
   github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_auth_role.go:500 +0x22c
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.flattenRoleConditionTerms({0xc0008332c0, 0x1, 0x10c40ad?})
   github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_auth_role.go:481 +0x19e
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.flattenRoleConditionNode({0x0, 0x0, 0xc000553c68, 0xc000bc4940, 0xc000553dd0})
   github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_auth_role.go:464 +0xbe
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.flattenRolePermissionPolicies({0xc0000fe000, 0x22, 0xb?})
   github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_auth_role.go:449 +0x269
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.readAuthRole.func1()
   github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_auth_role.go:266 +0x715
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1()
   github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/resource/wait.go:27 +0x56
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
   github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/resource/state.go:110 +0x207
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
   github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/resource/state.go:83 +0x1d8

Error: The terraform-provider-genesyscloud_v1.9.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
more logs:
[terraform.log](https://github.com/MyPureCloud/terraform-provider-genesyscloud/files/10112693/terraform.log)

**Comment by charliecon** [comment]
> Hello,
> 
> I have issue with exporting data using "genesyscloud_tf_export" and resource type "genesyscloud_auth_role"
> 
> ```
> genesyscloud_tf_export.export: Creating...
> ╷
> │ Error: Plugin did not respond
> │
> │   with genesyscloud_tf_export.export,
> │   on main.tf line 18, in resource "genesyscloud_tf_export" "export":
> │   18: resource "genesyscloud_tf_export" "export" {
> │
> │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
> ╵
> 
> Stack trace from the terraform-provider-genesyscloud_v1.9.0 plugin:
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd2b84c]
> 
> goroutine 576 [running]:
> github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.flattenRoleConditionOperands({0xc0002cb000, 0x3, 0x10c117a?})
>    github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_auth_role.go:500 +0x22c
> github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.flattenRoleConditionTerms({0xc0008332c0, 0x1, 0x10c40ad?})
>    github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_auth_role.go:481 +0x19e
> github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.flattenRoleConditionNode({0x0, 0x0, 0xc000553c68, 0xc000bc4940, 0xc000553dd0})
>    github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_auth_role.go:464 +0xbe
> github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.flattenRolePermissionPolicies({0xc0000fe000, 0x22, 0xb?})
>    github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_auth_role.go:449 +0x269
> github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.readAuthRole.func1()
>    github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_auth_role.go:266 +0x715
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1()
>    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/resource/wait.go:27 +0x56
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
>    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/resource/state.go:110 +0x207
> created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
>    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/resource/state.go:83 +0x1d8
> 
> Error: The terraform-provider-genesyscloud_v1.9.0 plugin crashed!
> 
> This is always indicative of a bug within the plugin. It would be immensely
> helpful if you could report the crash with the plugin's maintainers so that it
> can be fixed. The output above should help diagnose the issue.
> ```
> 
> more logs: [terraform.log](https://github.com/MyPureCloud/terraform-provider-genesyscloud/files/10112693/terraform.log)

Hello, 

Thank you for raising this issue. We will assign it to a member of our dev team, fix the problem, and release a new version in the coming days. 

Charlie

**Comment by charliecon** [comment]
@sienikam v1.10.0 has been released and it addresses this bug. Thanks again for bringing this to our attention!
