### ISSUE TITLE
The argument "file_content_hash" is required, but no definition was found

### ISSUE THREAD

**Issue by asadsaqlain** [MyPureCloud/terraform-provider-genesyscloud#404]
We receive following error if we use any version higher than 1.7.0.

on xxxxxxx\xxxxxx\genesyscloud_CM.tf line 55, in resource "genesyscloud_flow" "xxxxxxxxxxxxx":
resource "genesyscloud_flow" "xxxxxxxxxxxxxx"

The argument "file_content_hash" is required, but no definition was found

side note: Terraform version = 1.36

**Comment by charliecon** [comment]
Hello

Yes, `file_content_hash` is a new required field. Here: [https://registry.terraform.io/providers/MyPureCloud/genesyscloud/latest/docs/resources/flow](https://registry.terraform.io/providers/MyPureCloud/genesyscloud/latest/docs/resources/flow), you can find the documentation around this field along with an example of how it is set. 

Hope this helps,
Charlie

**Comment by asadsaqlain** [comment]
ah great. I'll add that to config. Thanks Charlie!
