### ISSUE TITLE
Getting error while make build

### ISSUE THREAD

**Issue by dharshinithilagar** [MyPureCloud/terraform-provider-genesyscloud#409]
PS C:\Users\username\Downloads\terraform-provider-genesyscloud> make build
mkdir -p ./dist
The syntax of the command is incorrect.
make: *** [GNUmakefile:23: build] Error 1

**Comment by carnellj-genesys** [comment]
Hi dharshinithilagar,

We use make files that are based on the linux operating system.  You are running on a Windows OS and many of the commands do not work.  You will need to follow the commands to build by reverse engineering into Windows.

Thanks,
    John
