### ISSUE TITLE
Add contacts form CSV file to Genesys Cloud outbound contact list resource

### ISSUE THREAD

**Issue by emad-kamel** [MyPureCloud/terraform-provider-genesyscloud#489]
Hi
I'm trying to create a **genesyscloud_outbound_contact_list** resource and need to attach contacts list CSV file, but the module can't handle file attachment nor have the upload API endpoint.
So, could you add this feature in the next release? 
Thanks

**Comment by charliecon** [comment]
Hi Emad,

Thank you for your message.
 
This feature is upcoming in our queue. We will implement it and get it out to you as soon as possible.

Regards
Charlie
