### ISSUE TITLE
Plugin stopped while exporting 

### ISSUE THREAD

**Issue by svendecock** [MyPureCloud/terraform-provider-genesyscloud#490]
Hello,

While trying to export the objects of an org that contains an SMS number, we get the error message below.
This applies for version 1.13 & 1.14 of the TF provider. The same config file works perfectly on other orgs without SMS numbers.
One note, we are in a country where we need to request SMS numbers manually via Genesys Support, maybe this is somehow related? 

Please let me know what additional information is required to debug this.

Kind regards,
Sven Decock

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # genesyscloud_tf_export.export will be created
  + resource "genesyscloud_tf_export" "export" {
      + directory             = "./genesyscloud"
      + export_as_hcl         = false
      + id                    = (known after apply)
      + include_state_file    = true
      + log_permission_errors = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

genesyscloud_tf_export.export: Creating...
╷
│ Error: Plugin did not respond
│
│   with genesyscloud_tf_export.export,
│   on demo.tf line 17, in resource "genesyscloud_tf_export" "export":
│   17: resource "genesyscloud_tf_export" "export" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-genesyscloud_v1.14.0.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x189c69b]

goroutine 280 [running]:
terraform-provider-genesyscloud/genesyscloud.getAllRoutingSmsAddress({0xc000d4bd30?, 0xdacdee?}, 0xc0003f09c0)
        terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_routing_sms_addresses.go:92 +0x1bb
terraform-provider-genesyscloud/genesyscloud.getAllWithPooledClient.func1({0x1f1ddd8, 0xc00083f980})
        terraform-provider-genesyscloud/genesyscloud/sdk_client_pool.go:149 +0x1db
terraform-provider-genesyscloud/genesyscloud.(*ResourceExporter).LoadSanitizedResourceMap(0xc0006dec80, {0x1f1ddd8?, 0xc00083f980?}, {0x1be957d, 0x20}, {0x2621220?, 0x0, 0x0})
        terraform-provider-genesyscloud/genesyscloud/resource_exporter.go:111 +0x7a
terraform-provider-genesyscloud/genesyscloud/tfexporter.buildSanitizedResourceMaps.func1({0x1be957d, 0x20}, 0xc0006dec80)
        terraform-provider-genesyscloud/genesyscloud/tfexporter/resource_genesyscloud_tf_export.go:560 +0x15e
created by terraform-provider-genesyscloud/genesyscloud/tfexporter.buildSanitizedResourceMaps
        terraform-provider-genesyscloud/genesyscloud/tfexporter/resource_genesyscloud_tf_export.go:557 +0x136

Error: The terraform-provider-genesyscloud_v1.14.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by charliecon** [comment]
Hi Sven

Thanks for reporting this bug. It looks like there are some objects being returned from the function `getAllRoutingSmsAddress` that our code isn't prepared to handle. 

We will create a ticket and get to work on this ASAP. If we need any more info we'll contact you here.

Thanks again
Charlie

**Comment by dginty4** [comment]
Hi Sven,

I'm having a little trouble replicating the issue. Would you by any chance be able to give me the output when you use `getAllRoutingSmsAddress` in your org? You can use the CLI tool for this by running the command `gc routing sms addresses list`  or you could use the api explorer use the endpoint, https://developer.genesys.cloud/devapps/api-explorer#get-api-v2-routing-sms-addresses, you could also use one of the SDK's if you like. This would help me figure out what might be causing the problem.

Thanks,
Declan

**Comment by dginty4** [comment]
Hi Sven,

I am having trouble replicating the issue. Would you be able to send me output when you run `getAllRoutingSmsAddresses`? You can blankout any sensitive information. This will help me figure out if any unexpected data is being returned that might be causing the issue. You can run `getAllRoutingSmsAddresses` using the CLI tool with the command `gc routing sms addresses list`. You can also use the SDK's for this or use the api explorer to hit the endpoint. This is the link for the endpoint on api explorer that explains how to do this https://developer.genesys.cloud/devapps/api-explorer#post-api-v2-routing-sms-addresses

Thanks,
Declan

**Comment by dginty4** [comment]
Hi @svendecock,

Were you able to fix the issue? If not could would you be able to provide a little more info? i am unable to replicate the issue.

Thanks,
Declan
