### ISSUE TITLE
genesyscloud_architect_datatable has multiple "property" attributes which stops for_each/dynamic column number

### ISSUE THREAD

**Issue by gordon-walker** [MyPureCloud/terraform-provider-genesyscloud#497]
When using resource genesyscloud_architect_datatable to create a table multiple property attributes are required to be defined for each column.  This means that no for_each looping can occur ( or variable creation) for the number of columns because terraform does not allow for the attribute name to be dynamic.

This attribute should be moved into a list or set as this is what the data reflects.  Also to note the extracts created by tf_export ( tfstate and json) reflect this, as seen below:

JSON

       "properties": [
          {
            "default": null,
            "name": "key",
            "title": "business unit",
            "type": "string"
          },
          {
            "default": null,
            "name": "name",
            "title": "slot1",
            "type": "string"
          },

tfState

           "properties.#": "7",
            "properties.0.default": "",
            "properties.0.name": "key",
            "properties.0.title": "business unit",
            "properties.0.type": "string",
            "properties.1.default": "",
            "properties.1.name": "name",
            "properties.1.title": "slot1",
            "properties.1.type": "string",

Thanks
Gordon

**Comment by dginty4** [comment]
Hi Gordon,

We have investigated the issue and we have decided to leave the resource as is. The behaviour of the resource is as intended. Terraform does not seem to allow properties to be defined as arrays of custom objects like the property block. We have however found a way that you can use a loop to create the property blocks like so:

`resource "genesyscloud_architect_datatable" "customers" {
  name        = "Customers"
  division_id = "ce4eb5f0-f870-4f68-93d6-59e1a6dd86bd"
  description = "Table of Customers"

  dynamic "properties" {
    for_each = var.properties
    content {
      name    = properties.value.name
      type    = properties.value.type
      title   = properties.value.title
      default = properties.value.default
    }
  }
}`

This example assumes you have a variable containing each of the property objects. An example variable would look like so:

`variable "properties" {
  type = list(object({
    name    = string
    type    = string
    title   = string
    default = string
  }))
  default = [
    {
      name  = "key"
      type  = "string"
      title = "Email"
      default = ""
    },
    {
      name  = "identifier"
      type  = "integer"
      title = "Customer Identifier"
      default = ""
    },
    {
      name    = "deleted"
      type    = "boolean"
      title   = "Is Deleted"
      default = "false"
    }
  ]
}`

I hope this helps.

Regards,
Declan

**Comment by gordon-walker** [comment]
Thanks Declan,
I have tried this workaround and it works great for me too.
Thanks for your teams help
Gordon
