### ISSUE TITLE
Call Routing Number are getting Deleted if any issue occurs at the time of update

### ISSUE THREAD

**Issue by siva-racubetech** [MyPureCloud/terraform-provider-genesyscloud#525]
Hi Team,

we run the terraform and in the plan it doesnot show any phone number as removal but when we apply we ran in to **API Error: 400 - Field 'didPoolId' is required and cannot be empty.** and after this all the existing number got removed from the Call Routing

Thanks.

**Comment by carnellj-genesys** [comment]
Hi Siva,

We will try to reproduce on our end.  Can you provide an example snippet of the Terraform resource(s) that caused the error.

Thanks,
    John
