### ISSUE TITLE
Site > Phone Edge Assignments > Terraform

### ISSUE THREAD

**Issue by asadsaqlain** [MyPureCloud/terraform-provider-genesyscloud#535]
We’ve hit into a new issue with the sites. I see we can't do the "phone Edge Assignment" from the terraform to a specific site. Even if I save it in UI and export Terraform doesn’t include these settings. This means we’ve to work with some of our sites out of cx as a code which is not desirable. Can you help us with this? Thanks!

**Comment by carnellj-genesys** [comment]
Internally tracking work with DEVENGAGE-1925.

**Comment by carnellj-genesys** [comment]
Issue has been fixed.  Should be out with version 1.17.0 of the next provider.

**Comment by asadsaqlain** [comment]
Thanks a lot John for another fast resolution.

**Comment by asadsaqlain** [comment]
Hi @carnellj-genesys today we update our provider version to 1.18.0 and see that we can now add the primary/secondary phone sites to a specific site. Thanks for this!

But there's a small issue. If you don't a primary/secondary site to this site it'll be always seen as a change and will change this specific site (we have around 8 sites) with every run and is not very handy. Can you fix this otherwise it's a annoying unnecessary changes to the sites. please check the screenshot added below. Thanks!

![2023-08-14 17_07_02-GENESYS » genesys-cloud-sc » Dev #524 Console  Jenkins](https://github.com/MyPureCloud/terraform-provider-genesyscloud/assets/80473200/0a7db662-bac4-4259-92cb-010151e58bef)

**Comment by carnellj-genesys** [comment]
Hi Asad,

Sorry, but I can't do that.  We needed to apply a set of logic around primary and secondary sites so the values aren't just an application of whatever data is passed into them.  They are computed so you will always have them coming up with a change value in the plan.

Thanks,
    John Carnell
    Director, Developer Engagement



________________________________

**Comment by asadsaqlain** [comment]
Okay thanks John, we can live with this :)

**Comment by carnellj-genesys** [comment]
Hi Asad,

Sorry I would have liked to make the change, but we are also constrained by the behavior of our own APIs. 🙂

Thanks,
    John
________________________________

**Comment by asadsaqlain** [comment]
no worries, it's at least doing the work which was very important for us ;). Thanks!
