### ISSUE TITLE
genesyscloud_recording_media_retention_policy when has multiple ids in queues condition, only the first one is saved

### ISSUE THREAD

**Issue by eelhilali** [MyPureCloud/terraform-provider-genesyscloud#540]
I create à genesyscloud_recording_media_retention_policy whith conditions:
media_policies {
          ~ call_policy {
              ~ conditions {
                  ~ for_queue_ids   = [id1,id2,id3]

Only the first id is savecd when i check on the UI, and when i try terraform apply again it shows 1 change all time and never apply.

Used provider version: 1.15.0
The bug still also in 1.16.0

**Comment by carnellj-genesys** [comment]
Fixed and should be out in release 1.18
