### ISSUE TITLE
edges_trunkbasesettings, error with new setting "inboundsiteid"

### ISSUE THREAD

**Issue by StrikerExtreem** [MyPureCloud/terraform-provider-genesyscloud#657]
Hi,

There is a new option when creating an external trunk, Inbound -> Number Plan Site.
When i export, this field does not seem to be in the export.
And when i try to modify a trunk through terraform, where the live version has the field set, i got an error:
[{"errorCode":"REQUIRED_FIELD_MISSING","fieldName":"inboundSiteId"}]}
"status":"400 Bad Request","error":{"status":400,"message":"Field 'inboundSiteId' is required and cannot be empty."

But when i have a blank environment, with no trunks, i can create the trunk without the field "inboundSiteId" with no problem

Possible something to add in the export code? And also possibly, i need to add the field to the terraform resource, but i do not know where.

Kind regards,

Addie

**Comment by carnellj-genesys** [comment]
Hi Addie,

Thanks for reporting this.  We have created an internal ticket to track this (DEVENGAGE-2243) and I will get someone looking at this soon.

**Comment by StrikerExtreem** [comment]
Hi,

I can see that inboundsiteid has been added to the terraform plugin, thanks!. But i think we have another problem now.
Since, according to the website: https://help.mypurecloud.com/articles/improve-inbound-call-handling-with-the-number-plan-site-feature/
_The site that you select controls the number plan that a trunk uses, both for transforms on inbound calls and for **subsequent outbound transfers** for calls that never flow through another site_

So, if the the newly created inbound site Y has an outbound route with trunk X, because of the need of the "subsequent outbound transfers" in the help webpage.
And Trunk X has "inboundSite" site Y. Both can never be created, because they depend on eachother, terraform also shows an error, when doing this.

Or must i read "subsequent outbound transfers" as "internal transfers only", then, there is no problem. Because the "inboundsite " does not need an outbound route.

Kind regards,
Addie

**Comment by carnellj-genesys** [comment]
Hi Striker,

I will need to chat with the Dev team about what the behavior of their underlying API is.  

Thanks,
   John

**Comment by StrikerExtreem** [comment]
Hi @carnellj-genesys 

Any news regarding this issue? Did you get any info back from dev, about this chicken/egg issue?

Kind regards,
Addie

**Comment by carnellj-genesys** [comment]
Hi Addie,

No update.  Still working it.

Thanks,
     John

**Comment by StrikerExtreem** [comment]
Hi John,

I see in another issue listed, that this is tracked under DEVTOOLING-477. Lets not keep both issues open.
Will close mine.

Kind regards,

Addie
