### ISSUE TITLE
How to retrieve the system proxy via terraform

### ISSUE THREAD

**Issue by kalakshmanakumar87** [MyPureCloud/terraform-provider-genesyscloud#701]
Hi All,

Hope every one doing good.

Please let me know how to get the system proxy setting via terraform

Thanks in advance for your response

**Comment by charliecon** [comment]
Hello

You can find an example of using our proxy in the readme here - [https://github.com/MyPureCloud/terraform-provider-genesyscloud#proxy-configuration](https://github.com/MyPureCloud/terraform-provider-genesyscloud#proxy-configuration) 

-Charlie

**Comment by kalakshmanakumar87** [comment]
Hi Charliecon,

Thanks for you response, 
I want to get the proxy setting at runtime from the system.

Thanks in advance for your response

**Comment by kalakshmanakumar87** [comment]
Hi Charliecon,

Our HTTP/HTTPS proxy requires client authentication using Windows domain user authentication, which is smart-card based 2FA. Since it's not a plain username and password, it's not clear how to specify it with Terraform. The proxy itself is reachable when configured as environmental variable HTTPS_PROXY, but it returns "Proxy Authentication Required" when attempting to init, and HTTPS_USER/HTTPS_PASSWORD doesn't help. So the question is rather how to authenticate in such conditions.

Thanks in advance for your response
