### ISSUE TITLE
Failed to install provider

### ISSUE THREAD

**Issue by NinjAk3** [MyPureCloud/terraform-provider-genesyscloud#90]
I am having issue with terraform init command. Seems to be getting the error below:

Initializing the backend...

Initializing provider plugins...
- Finding latest version of mypurecloud/genesyscloud...
- Installing mypurecloud/genesyscloud v0.12.0...

Error: Failed to install provider

Error while installing mypurecloud/genesyscloud v0.12.0: open .terraform\providers\registry.terraform.io\mypurecloud\genesyscloud\0.12.0\windows_amd64\terraform-provider-genesyscloud_v0.12.0.exe: The system cannot find the path specified.

I have tried with terraform v1.0.6, and v1.0.5, both getting the same error message.

**Comment by ronanwatkins** [comment]
Hi, sorry for taking so long to reply to this.
I think this may be a result of a Windows max path length issue.
Please see this article on how to increase the max path length: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by NinjAk3** [comment]
Thank you Ronan. That fixed the issue!
