### ISSUE TITLE
Provider incorrectly requires ring_num when using a set of objects instead of a single object during queue creation

### ISSUE THREAD

**Issue by natereprogle** [MyPureCloud/terraform-provider-genesyscloud#928]
When creating a queue using the following:

```terraform
resource "genesyscloud_routing_queue" "queue" {
  name                    = "Terraform Customer Service"
  description             = "The customer service queue"
  members {
    user_id  = data.genesyscloud_user.user.id
  }
}
```

It does not require a `ring_num` value. However, when creating a queue using this method:

```terraform
resource "genesyscloud_routing_queue" "queue" {
  name                    = "Terraform Customer Service"
  description             = "The customer service queue"
  members = [
    {
      user_id  = data.genesyscloud_user.user.id
    },
    {
      user_id  = data.genesyscloud_user.user_two.id
    }
  ]
}
```

The console output incorrectly states that ring_num is a required attribute, which goes against what the [Terraform docs state](https://registry.terraform.io/providers/MyPureCloud/genesyscloud/latest/docs/resources/routing_queue). Providing a ring_num allows the job to continue successfully.

![image](https://github.com/MyPureCloud/terraform-provider-genesyscloud/assets/4064388/f0164680-0f55-4723-95fc-d0f561ae6e02)

**Comment by charliecon** [comment]
Hi @natereprogle 

Thanks for bringing this to our attention. 

You won't see this error if you define your members like this:

```hcl
  members {
    user_id = "123"
  }
  members {
    user_id = "321"
  }
```

At the moment, I don't understand why the error occurs when you define your members list with square brackets. We will look into it as soon as we can and decide then if a bug fix is necessary.

Thanks again!
Charlie

**Comment by natereprogle** [comment]
> Hi @natereprogle 
> 
> 
> 
> Thanks for bringing this to our attention. 
> 
> 
> 
> You won't see this error if you define your members like this:
> 
> 
> 
> ```hcl
> 
>   members {
> 
>     user_id = "123"
> 
>   }
> 
>   members {
> 
>     user_id = "321"
> 
>   }
> 
> ```
> 
> 
> 
> At the moment, I don't understand why the error occurs when you define your members list with square brackets. We will look into it as soon as we can and decide then if a bug fix is necessary.
> 
> 
> 
> Thanks again!
> 
> Charlie

Awesome, thanks for the assistance and workaround.
