### ISSUE TITLE
BYMONTHDAY not working anymore with multiple days

### ISSUE THREAD

**Issue by StrikerExtreem** [MyPureCloud/terraform-provider-genesyscloud#947]
Hi,

Last time i created a Christmas schedule, i could add both the 25th and 26th in one schedule. That seems not possible anymore.
But looking into the API and doing a GET, i get the rrule with 25,26 in it.

Error: Invalid BYMONTHDAY attribute. Should be a valid day of the month (1-31) without leading zeros for single-digit days.
  with genesyscloud_architect_schedules.Christmas,
  on architect.tf line 561, in resource "genesyscloud_architect_schedules" "Christmas":
561:     rrule       = "FREQ=YEARLY;INTERVAL=1;BYMONTH=12;BYMONTHDAY=25,26"

Not sure if the interpretation of a rrule has changed somewhere.

Kind regards,

Addie

**Comment by BrianMoyles** [comment]
Hi Addie,
Thank you for Reporting this.
This seems to be a bug and i have created a ticket to resolve this.
Regards,
Brian

**Comment by BrianMoyles** [comment]
Hi Addie,
This issue has now been resolved 
Regards,
Brian

**Comment by StrikerExtreem** [comment]
Hi Brian,

Thanks, yesterday i used the new version, and i had no problems. Good to see!

Regards,

Addie
