### ISSUE TITLE
Attribute message_column of sms_config for resource genesyscloud_outbound_messagingcampaign should not be required

### ISSUE THREAD

**Issue by TaisukChoi** [MyPureCloud/terraform-provider-genesyscloud#993]
Right now, attribute `message_column` of `sms_config` block in resource genesyscloud_outbound_messagingcampaign is **Required**. Problem is, GC requires either `message_column` or `content_template_id`, not both at the same time.

But because `message_column` is required, it's not possible to specify `content_template_id`. If you specify both there will be below error:

`Error: Failed to create outbound messagingcampaign Campaign error: API Error: 400 - Only one of the messaging options should be set - messageColumn or contentTemplateId (efc3267f-6f43-4f4d-9339-8ffae03b8e33)`

**Comment by dginty4** [comment]
Fixed in https://github.com/MyPureCloud/terraform-provider-genesyscloud/pull/1013
